name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install and Lint Client
      working-directory: ./client
      run: |
        npm ci
        npm run lint
    
    - name: Install and Lint Server
      working-directory: ./server
      run: |
        npm ci
        npm run lint

    - name: Check Client Formatting
      working-directory: ./client
      run: npm run format:check

    - name: Check Server Formatting
      working-directory: ./server
      run: npm run format:check