name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install and Lint Client
      working-directory: ./client
      run: |
        npm install
        npm run lint
        npm run format:check
    
    - name: Install and Lint Server
      working-directory: ./server
      run: |
        npm install
        npm run lint
        npm run format:check